
### Register (non admin user)

POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "username",
    "email": "email@email.com",
    "password": "password"
}

### Login (non admin user)

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "email@email.com",
    "password": "password"
}

### Login admin // already seeded

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com", 
    "password": "admin"
}

### Validate

GET http://localhost:3000/auth/validate HTTP/1.1


### Logout

POST http://localhost:3000/auth/logout HTTP/1.1

### get all users

GET http://localhost:3000/users